# Generated by Django 3.1.7 on 2021-03-13 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('de_quien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCharla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('de_quien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharlaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa_charlas_app.charla')),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa_charlas_app.texto')),
            ],
        ),
        migrations.AddField(
            model_name='charla',
            name='textos',
            field=models.ManyToManyField(through='pa_charlas_app.CharlaItem', to='pa_charlas_app.Texto'),
        ),
        migrations.AddField(
            model_name='charla',
            name='tipo',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pa_charlas_app.tipocharla'),
        ),
    ]
