# Generated by Django 3.1.7 on 2021-03-20 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pa_charlas_app', '0002_auto_20210314_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_visita', models.DateTimeField(default=django.utils.timezone.now)),
                ('charla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa_charlas_app.charla')),
                ('de_quien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
