# Generated by Django 3.1.7 on 2021-04-10 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pa_charlas_app', '0003_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('de_quien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa_charlas_app.texto')),
                ('voto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa_charlas_app.voto')),
            ],
        ),
    ]
