# Generated by Django 3.1.7 on 2021-04-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_charlas_app', '0005_auto_20210410_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='charlaitem',
            name='nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charlaitem',
            name='orden',
            field=models.CharField(default='', max_length=50),
        ),
    ]
