# Generated by Django 3.1.7 on 2021-05-02 01:52

from django.db import migrations

#VER: https://realpython.com/data-migrations/
#VER: https://docs.djangoproject.com/en/3.2/topics/migrations/#data-migrations
def charlaitem_agregar_orden_si_no_tiene(apps, schema_editor):
	CharlaItem= apps.get_model("pa_charlas_app", "CharlaItem")	
	for chit in CharlaItem.objects.filter(orden='').select_related('texto').all():
		chit.orden= chit.texto.fh_creado.strftime('_%y%m%d%H%M%S')
		chit.save()
			

class Migration(migrations.Migration):

	dependencies = [
		('pa_charlas_app', '0006_auto_20210415_2133'),
	]

	operations = [
		migrations.RunPython(charlaitem_agregar_orden_si_no_tiene)		
	]
