# Generated by Django 3.1.7 on 2021-05-02 03:54

from django.db import migrations

def crear_tipo_charla(apps, schema_editor):
    TipoCharla= apps.get_model('pa_charlas_app','TipoCharla')	
    TipoCharla(titulo='Hilo').save()
	

class Migration(migrations.Migration):

    dependencies = [
        ('pa_charlas_app', '0007_auto_20210502_0152'),
    ]

    operations = [
        migrations.RunPython(crear_tipo_charla)
    ]
