# Generated by Django 3.1.7 on 2021-05-09 21:33

from django.db import migrations

def crear_tipo_charla(apps, schema_editor):
    TipoCharla= apps.get_model('pa_charlas_app','TipoCharla')	
    TipoCharla(titulo='Voto').save()

class Migration(migrations.Migration):
    dependencies = [
        ('pa_charlas_app', '0009_imagen'),
    ]

    operations = [
        migrations.RunPython(crear_tipo_charla)
    ] 
