# Generated by Django 3.1.7 on 2021-05-28 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa_charlas_app', '0012_auto_20210527_2247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BancoTx',
        ),
    ]
