# Generated by Django 3.1.7 on 2021-05-28 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pa_charlas_app', '0013_delete_bancotx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=200)),
                ('cuanto', models.IntegerField()),
                ('que', models.CharField(max_length=200)),
                ('quien_da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancotx_da', to=settings.AUTH_USER_MODEL)),
                ('quien_hace', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bancotx_hace', to=settings.AUTH_USER_MODEL)),
                ('quien_recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancotx_recibe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
